name: Deploy to Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PORTFOLIO_SITE_PATH: './hosted-repo'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone hosted source repository
        uses: actions/checkout@v4
        with:
          repository: antazoey/antazoey.github.io
          ref: main
          path: ./hosted-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Install less
        run: npm install -g less

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Deploy
        run: npm run deploy

      - name: Push changes
        run: |
          cd $PORTFOLIO_SITE_PATH
          git add .
          git commit -m "Auto-deploy from CI" || echo "No changes to commit"
          git push origin main
