name: Deploy to Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone hosted source repository
        uses: actions/checkout@v2
        with:
          repository: antazoey/antazoey.github.io
          ref: main
          path: ${{ env.PORTFOLIO_SITE_PATH }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install less
        run: npm install -g less

      - name: Deploy
        run: npm run deploy

env:
  PORTFOLIO_SITE_PATH: './hosted-repo'
